select * from TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' AND TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' OR TAMANHO = '470 ml';

-- not

SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470 ml');


SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOT SABOR = 'Manga' AND TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga' OR SABOR = 'Laranja' OR SABOR = 'Melancia';

SELECT * FROM TABELA_DE_PRODUTOS
WHERE SABOR IN ('Manga', 'Laranja', 'Melancia');

SELECT * FROM TABELA_DE_PRODUTOS
WHERE (SABOR IN ('Manga', 'Laranja', 'Melancia')) AND (TAMANHO IN ('300 ml', '470 ml', '1 Litro'));



SELECT * FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Sao Paulo', 'Rio de Janeiro');

SELECT * FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Sao Paulo', 'Rio de Janeiro') AND IDADE >= 20;


SELECT * FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Sao Paulo', 'Rio de Janeiro') AND (IDADE >= 20 AND IDADE <= 25);

SELECT * FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Sao Paulo', 'Rio de Janeiro') AND (IDADE BETWEEN 20 AND 25);