SELECT 
    *
FROM 
    [TABELA_DE_CLIENTES];

SELECT 
    [CPF],
    [NOME],
    [BAIRRO],
    [CIDADE]
FROM 
    [TABELA_DE_CLIENTES];

SELECT 
    [NOME],
    [CPF],
    [BAIRRO],
    [CIDADE]
FROM 
    [TABELA_DE_CLIENTES];

-- Alias Colunas    
SELECT 
    [CPF] AS [IDENTIFICADOR],
    [NOME] AS [NOME CLIENTE],
    [BAIRRO] AS [NOME BAIRRO],
    [CIDADE] AS [NOME CIDADE] 
FROM
    [TABELA_DE_CLIENTES];

-- Alias Tabela
SELECT 
    [CPF] AS [IDENTIFICADOR],
    [NOME] AS [NOME CLIENTE],
    [BAIRRO] AS [NOME BAIRRO],
    [CIDADE] AS [NOME CIDADE] 
FROM
    [TABELA_DE_CLIENTES] TDC;

SELECT TDC.CPF, TDC.NOME, TDC.BAIRRO, TDC.CIDADE
FROM [TABELA_DE_CLIENTES] AS TDC;

SELECT TDC.*
FROM TABELA_DE_CLIENTES AS TDC;

SELECT
 TABELA_DE_CLIENTES.CPF,
 TABELA_DE_CLIENTES.NOME,
 TABELA_DE_CLIENTES.BAIRRO,
 TABELA_DE_CLIENTES.CIDADE
FROM TABELA_DE_CLIENTES;