SELECT name, recovery_model_desc 
FROM sys.databases 
WHERE name = 'dbVendas'

ALTER DATABASE [dbVendas] 
SET RECOVERY FULL;




SELECT DISTINCT [data] FROM tb_nota order by [data] DESC

CREATE TABLE tb_controle_backups 
(ID INTEGER, NOME VARCHAR(100), NUMERO_NOTAS INTEGER);

-- 1 DA MANHA - FULL (DATABASE WITH INT)

SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- Total Nota 226
EXEC IncluiNotasDia '2022-01-01'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (1, 'BACKUP FULL 1 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups
-- Total Nota 284

BACKUP DATABASE dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH INIT;

-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- Total Nota 115
EXEC IncluiNotasDia '2022-01-01'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (3, 'BACKUP INCREMENTAL 4 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 6 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 491
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 602
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (4, 'BACKUP INCREMENTAL 6 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 8 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 602
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 716
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (5, 'BACKUP INCREMENTAL 8 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 9 DA MANHÃ - FULL (DATABASE WITH DIFFERENTIAL)
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 716
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 805
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (6, 'BACKUP DIFFERENTIAL 9 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP DATABASE dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH DIFFERENTIAL;

-- 10 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 805
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 935
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (7, 'BACKUP INCREMENTAL 10 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 12 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 935
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1071
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (8, 'BACKUP INCREMENTAL 12 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 2 DA TARDE - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1071
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1186
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (9, 'BACKUP INCREMENTAL 2 PM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 2 DA TARDE - FULL (DATABASE WITH DIFFERENTIAL)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1186
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1263
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (10, 'BACKUP DIFFERENTIAL 2 PM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP DATABASE dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH DIFFERENTIAL;

-- 3 DA TARDE - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1236
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1364
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (11, 'BACKUP INCREMENTAL 3 PM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 5 DA TARDE - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1364
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1504
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (12, 'BACKUP INCREMENTAL 5 PM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 7 DA NOITE - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1504
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1626
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (13, 'BACKUP INCREMENTAL 7 PM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 9 DA NOITE - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1626
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM [tb_nota] WHERE [data] = '2022-01-01';
-- 1717
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (9, 'BACKUP INCREMENTAL 2 PM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;
