SELECT name, recovery_model_desc 
FROM sys.databases 
WHERE name = 'dbVendas'

ALTER DATABASE [dbVendas] 
SET RECOVERY FULL;




SELECT DISTINCT [data] FROM tb_nota order by [data] DESC

CREATE TABLE tb_controle_backups 
(ID INTEGER, NOME VARCHAR(100), NUMERO_NOTAS INTEGER);

-- 1 DA MANHA - FULL (DATABASE WITH INT)

SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- Total Nota 226
EXEC IncluiNotasDia '2022-01-01'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (1, 'BACKUP FULL 1 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups
-- Total Nota 284

BACKUP DATABASE dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH INIT;

-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- Total Nota 115
EXEC IncluiNotasDia '2022-01-01'
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (3, 'BACKUP INCREMENTAL 4 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 6 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 491
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 602
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (4, 'BACKUP INCREMENTAL 6 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 8 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 602
EXEC IncluiNotasDia '2022-01-01'
SELECT COUNT(*) FROM tb_nota WHERE [data] = '2022-01-01';
-- 716
DECLARE @NUM_NOTAS INTEGER;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota; 
INSERT INTO tb_controle_backups VALUES (5, 'BACKUP INCREMENTAL 8 AM', @NUM_NOTAS);
SELECT * FROM tb_controle_backups

BACKUP LOG dbVendas TO DISK = 'C:\Users\Igorn\Documents\Alura\Formacao_MSSQLSERVER\Curso_6_MSS22_Administrando_DB\Aula_02_Gerenciando_DB\Data\BACKUP\POLITICA_BACKUP_20220101.BAK' WITH NOINIT;

-- 9 DA MANHÃ - FULL (DATABASE WITH DIFFERENTIAL)


-- 10 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 12 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)
-- 2 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 2 DA TARDE - FULL (DATABASE WITH DIFFERENTIAL)
-- 3 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 5 DA TARDE - INCREMENTAL (LOG WITH NOINT)
-- 7 DA NOITE - INCREMENTAL (LOG WITH NOINT)
-- 9 DA NOITE - INCREMENTAL (LOG WITH NOINT)

