-- Alterando a tabela Clientes para adicionar a chave primária e not null.
ALTER TABLE [TABELA_CLIENTES] ALTER COLUMN [CPF] [CHAR] (11) NOT NULL;
ALTER TABLE [TABELA_CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTES PRIMARY KEY CLUSTERED ([CPF]);