CREATE DATABASE SUCOS_VENDAS;
USE SUCOS_VENDAS;

-- Entidade Clientes:
CREATE TABLE [TABELA_CLIENTES] (
    [CPF] [CHAR] (14) NOT NULL /*PRIMARY KEY*/,
    [NOME] [VARCHAR] (150) NOT NULL,
    [RUA] [VARCHAR] (150) NOT NULL,
    [COMPLEMENTO] [VARCHAR] (150) NULL,
    [BAIRRO] [VARCHAR] (150) NOT NULL,
    [ESTADO] [CHAR] (2) NOT NULL,
    [CEP] [CHAR] (9) NOT NULL,    
    [DATA_NASCIMENTO] [DATE] NOT NULL,
    [IDADE] [SMALLINT] NOT NULL,
    [SEXO] [CHAR] (1) NOT NULL,
    [LIMITE_CREDITO] [MONEY] NOT NULL,
    [VOLUME_MINIMO_COMPRA] [FLOAT] NOT NULL,
    [PRIMEIRA_COMPRA] [BIT] NOT NULL
);

-- Entidade Produtos:
CREATE TABLE [TABELA_PRODUTOS] (
    [CODIGO_PRODUTO] [VARCHAR] (20) NOT NULL PRIMARY KEY,
    [NOME_PRODUTO] [VARCHAR] (50) NOT NULL,
    [EMBALAGEM] [VARCHAR] (50) NOT NULL,
    [TAMANHO] [VARCHAR] (50) NOT NULL,
    [SABOR] [VARCHAR] (50) NOT NULL,
    [PRECO_LISTA] [SMALLMONEY] NOT NULL
);

-- Entidade Vendedores:
CREATE TABLE [TABELA_VENDEDORES] (
    [MATRICULA] [INT] NOT NULL PRIMARY KEY,
    [NOME_VENDEDOR] [VARCHAR] (100) NOT NULL,
    [PERCENTUAL_COMISSAO] [FLOAT] NOT NULL
);




-- Alterando a tabela Clientes para adicionar a chave primária e not null.
ALTER TABLE [TABELA_CLIENTES] ALTER COLUMN [CPF] [CHAR] (11) NOT NULL;
ALTER TABLE [TABELA_CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTES PRIMARY KEY CLUSTERED ([CPF]);