DECLARE @CPF VARCHAR(50)
DECLARE @NOME VARCHAR(50)
DECLARE @DATA_NASCIMENTO VARCHAR(50)
DECLARE @IDADE INT

SET @CPF = '1471156710'

SELECT
    @NOME = NOME,
    @DATA_NASCIMENTO = [DATA DE NASCIMENTO],
    @IDADE = IDADE
FROM
    [TABELA DE CLIENTES]
WHERE
    CPF = @CPF;

PRINT @NOME;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;


