DECLARE @MATRICULA VARCHAR(5);
DECLARE @NOME VARCHAR(100);
DECLARE @PERCENTUAL FLOAT;
DECLARE @DATA DATE;
DECLARE @FERIAS BIT;
DECLARE @BAIRRO VARCHAR(50);

SELECT * FROM [TABELA DE VENDEDORES];

SET @MATRICULA = '00240';
SET @NOME = 'Igor N.';
SET @PERCENTUAL = 0.10;
SET @DATA = '1999-11-27';
SET @FERIAS = 1;            
SET @BAIRRO = 'Pq. Pinheiros';

INSERT INTO [TABELA DE VENDEDORES]
 (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES
 (@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO);

SELECT * FROM [TABELA DE VENDEDORES];