SELECT [NOME], [BAIRRO]
FROM [TABELA_CLIENTES]
WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO] = 'Tijuca'
ORDER BY [BAIRRO];


-- Aplicando Filtro WHERE com AND.
SELECT [NOME], [ESTADO], [PRIMEIRA_COMPRA]
FROM [TABELA_CLIENTES]
WHERE [PRIMEIRA_COMPRA] = 1 AND [ESTADO] = 'SP'
ORDER BY [NOME];