-- Aplicando Filtro WHERE - 6.
SELECT [NOME] AS [NOME DO CLIENTE],
       [DATA_NASCIMENTO] AS [DATA DE NASCIMENTO]
FROM [TABELA_CLIENTES]
WHERE [DATA_NASCIMENTO] > '1995-12-31'
ORDER BY [DATA_NASCIMENTO];

-- 6.2.
SELECT [NOME] AS [NOME DO CLIENTE],
       [DATA_NASCIMENTO] AS [DATA DE NASCIMENTO]
FROM [TABELA_CLIENTES]
WHERE YEAR([DATA_NASCIMENTO]) > '1995' --MONTH --DAY
ORDER BY [DATA_NASCIMENTO];