-- Aplicando Filtro WHERE - 2.
SELECT *
FROM [TABELA_PRODUTOS]
WHERE [PRECO_LISTA] = 7.00;

-- Aplicando Filtro WHERE - 3.
SELECT *
FROM [TABELA_PRODUTOS]
WHERE [PRECO_LISTA] > 7.00
ORDER BY [PRECO_LISTA];

-- Aplicando Filtro WHERE - 4.
SELECT *
FROM [TABELA_PRODUTOS]
WHERE [PRECO_LISTA] <= 7.00
ORDER BY [PRECO_LISTA];

-- Aplicando Filtro WHERE - 5.
SELECT *
FROM [TABELA_PRODUTOS]
WHERE [EMBALAGEM] > 'Lata';

