UPDATE
    [TABELA_PRODUTOS]
SET
    [PRECO_LISTA] = [PRECO_LISTA] * 0.90
WHERE
    [EMBALAGEM] = 'Lata'; 


-- COD-PROD: '1088126' 
SELECT
    *
FROM
    [TABELA_PRODUTOS]
WHERE
    [CODIGO_PRODUTO] = '1088126';

UPDATE
    [TABELA_PRODUTOS]  
SET [EMBALAGEM] = 'Garrafa', 
    [PRECO_LISTA] = 8.10
WHERE
    [CODIGO_PRODUTO] = '1088126';


-- COD-PROD: '1004327'
DELETE FROM 
    [TABELA_PRODUTOS]
WHERE 
    [CODIGO_PRODUTO] = '1004327';