SELECT COUNT(*) FROM [ITENS NOTAS FISCAIS];
SELECT COUNT(*) FROM [NOTAS FISCAIS];
SELECT COUNT(*) FROM [TABELA DE CLIENTES];
SELECT COUNT(*) FROM [TABELA DE PRODUTOS];
SELECT COUNT(*) FROM [TABELA DE VENDEDORES];
