DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT;
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(200));
DECLARE @CONTADOR_NOTAS INT;

SET @LIMITE_MINIMO = 1;
SET @LIMITE_MAXIMO = 1000000;   

SET NOCOUNT ON
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN

    SELECT @CONTADOR_NOTAS = COUNT(*)
    FROM [NOTAS FISCAIS]
    WHERE NUMERO = @LIMITE_MINIMO;

    IF @CONTADOR_NOTAS > 0
        BEGIN
            INSERT INTO @TABELA_NUMEROS ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'É NOTA FISCAL')
        END
    ELSE
        BEGIN
            INSERT INTO @TABELA_NUMEROS ([NUMERO], [STATUS]) VALUES (@LIMITE_MINIMO, 'NÃO É FISCAL')
        END
    SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1;
END;


SELECT * FROM @TABELA_NUMEROS ORDER BY [NUMERO] ASC;

SELECT MIN([NUMERO]) AS [MINIMO], MAX([NUMERO]) AS [MAXIMO] FROM @TABELA_NUMEROS;