EXEC IncluiNotasDias '2022-03-03'
SELECT COUNT(*) FROM tb_nota
--3564

RESTORE HEADERONLY FROM DISK = 'F:\DATA\BACKUP\DBVENDAS_3.BAK';

USE MASTER
DROP DATABASE dbVendas
RESTORE DATABASE dbVendas FROM DISK = 'F:\DATA\BACKUP\DBVENDAS_3.BAK' WITH RECOVERY;