SELECT *
FROM [TABELA DE CLIENTES];

SELECT COUNT(*)
FROM [TABELA DE CLIENTES];

SELECT X.CPF, X.NOME
FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY CPF) AS RowNum, *
    FROM [TABELA DE CLIENTES]
) X
WHERE X.RowNum = 3;

--
DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;

SELECT @NUMERO_CLIENTES = COUNT(*)
FROM [TABELA DE CLIENTES];
SET @I = 1;

WHILE @I <= @NUMERO_CLIENTES
BEGIN
    SELECT @CPF = X.CPF, @NOME = X.NOME
    FROM (
        SELECT ROW_NUMBER() OVER (ORDER BY CPF) AS RowNum, *
        FROM [TABELA DE CLIENTES]
    ) X
    WHERE X.RowNum = @I;
    PRINT @CPF + ' - ' +@NOME
    SET @I = @I + 1;
END;