SELECT *
FROM [TABELA DE CLIENTES];

SELECT COUNT(*)
FROM [TABELA DE CLIENTES];

SELECT X.CPF, X.NOME
FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY CPF) AS RowNum, *
    FROM [TABELA DE CLIENTES]
) X
WHERE X.RowNum = 3;

--
DECLARE @CPF VARCHAR(11);
DECLARE @NOME VARCHAR(100);
DECLARE @NUMERO_CLIENTES INT;
DECLARE @I INT;
DECLARE @MES INT, @ANO INT;
DECLARE @TOTAL_VENDAS FLOAT;

SET @MES = 1;
SET @ANO = 2015;

SELECT @NUMERO_CLIENTES = COUNT(*)
FROM [TABELA DE CLIENTES];
SET @I = 1;

WHILE @I <= @NUMERO_CLIENTES
BEGIN
    SELECT @CPF = X.CPF, @NOME = X.NOME
    FROM (
        SELECT ROW_NUMBER() OVER (ORDER BY CPF) AS RowNum, *
        FROM [TABELA DE CLIENTES]
    ) X
    WHERE X.RowNum = @I;

    SELECT 
    @TOTAL_VENDAS = SUM(ITF.QUANTIDADE * ITF.[PREÇO])
    FROM [NOTAS FISCAIS] NF
    INNER JOIN [ITENS NOTAS FISCAIS] ITF
    ON NF.NUMERO = ITF.NUMERO
    WHERE NF.CPF = @CPF
    AND YEAR(NF.DATA) = @ANO AND MONTH(NF.DATA) = @MES;

    PRINT 'Vendas para: ' + CONVERT(VARCHAR(10), @CPF) + ' - ' + @NOME + ' No mês ' + CONVERT(VARCHAR(2),@MES) + ' E ano ' + CONVERT(VARCHAR(4), @ANO) + ' Foi de R$: ' + CONVERT(VARCHAR(20), @TOTAL_VENDAS);
    SET @I = @I + 1;
END;










SELECT 
SUM(ITF.QUANTIDADE * ITF.[PREÇO])
FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] ITF
ON NF.NUMERO = ITF.NUMERO
WHERE NF.CPF = '1471156710'
AND YEAR(NF.DATA) = 2015 AND MONTH(NF.DATA) = 1;