/*
Para usar o GROUP BY, é necessário que haja na seleção de campos pelo menos um campo onde é aplicado uma função de AGREGAÇÃO.

EXEMPLO:
SUM = SOMA
AVG = MÉDIA
MIN = MÍNIMO
MAX = MÁXIMO 
*/

SELECT
    *
FROM
    TABELA_DE_CLIENTES;

SELECT
    CIDADE,
    IDADE
FROM
    TABELA_DE_CLIENTES;

SELECT
    CIDADE,
    IDADE
FROM
    TABELA_DE_CLIENTES
ORDER BY
    CIDADE, IDADE;

SELECT
    CIDADE,
    SUM(IDADE) AS SOMA_IDADE,
    SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE_CREDITO
FROM
    TABELA_DE_CLIENTES
GROUP BY
    CIDADE; 

SELECT
    CIDADE,
    AVG(IDADE) AS MEDIA_IDADE,
    SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE_CREDITO
FROM
    TABELA_DE_CLIENTES
GROUP BY
    CIDADE; 

SELECT
    CIDADE,
    COUNT(*) AS TOTAL_CLIENTES
FROM
    TABELA_DE_CLIENTES
GROUP BY
    CIDADE;

SELECT
    EMBALAGEM,
    COUNT(*) AS TOTAL_PRODUTOS
FROM
    TABELA_DE_PRODUTOS
GROUP BY
    EMBALAGEM;

SELECT
    EMBALAGEM,
    COUNT(*) AS TOTAL_PRODUTOS
FROM
    TABELA_DE_PRODUTOS
WHERE
    SABOR = 'Laranja'
GROUP BY
    EMBALAGEM;