SELECT
    *
FROM
    [TABELA_DE_CLIENTES];

SELECT
    ESTADO,
    SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM
    TABELA_DE_CLIENTES
GROUP BY
    ESTADO;

-- Não é possível utilizar campo de agregação no Where.
SELECT 
    ESTADO,
    SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM
    TABELA_DE_CLIENTES 
WHERE
    SUM(LIMITE_DE_CREDITO) >= 900000 
GROUP BY
    ESTADO;

-- Filtros de Agregação são Filtros a partir do 'HAVING'
SELECT
    ESTADO,
    SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM
    TABELA_DE_CLIENTES
GROUP BY
    ESTADO 
HAVING
    SUM(LIMITE_DE_CREDITO) >= 900000;

SELECT
    EMBALAGEM,
    MAX(PRECO_DE_LISTA) AS PRECO,
    MIN(PRECO_DE_LISTA) AS PRECO 
FROM
    TABELA_DE_PRODUTOS
GROUP BY
    EMBALAGEM;

SELECT
    EMBALAGEM,
    MAX(PRECO_DE_LISTA) AS PRECO,
    MIN(PRECO_DE_LISTA) AS PRECO 
FROM
    TABELA_DE_PRODUTOS
WHERE
    PRECO_DE_LISTA >= 10
GROUP BY
    EMBALAGEM;

SELECT
    EMBALAGEM,
    MAX(PRECO_DE_LISTA) AS PRECO,
    MIN(PRECO_DE_LISTA) AS PRECO 
FROM
    TABELA_DE_PRODUTOS
WHERE
    PRECO_DE_LISTA >= 10 
GROUP BY
    EMBALAGEM
HAVING
    MAX(PRECO_DE_LISTA) >=20;