USE SUCOS_FRUTAS;

SELECT COUNT(*) FROM [ITENS_NOTAS_FISCAIS];
SELECT COUNT(*) FROM [NOTAS_FISCAIS];
SELECT COUNT(*) FROM [TABELA_DE_CLIENTES];
SELECT COUNT(*) FROM [TABELA_DE_PRODUTOS];
SELECT COUNT(*) FROM [TABELA_DE_VENDEDORES];
