SELECT RAND()

SELECT ROUND(((500 - 100 - 1) * RAND() + 100), 0)

CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VAL_ALETORIO;

SELECT * FROM VW_ALEATORIO;

CREATE FUNCTION NumeroAleatorio(@VAL_MIN INT, @VAL_MAX INT)
RETURNS INT
BEGIN
    DECLARE @ALEATORIO INT
    DECLARE @VAL_ALEATORIO FLOAT
    SELECT @VAL_ALEATORIO = VAL_ALETORIO FROM VW_ALEATORIO
    SET @ALEATORIO = ROUND(((@VAL_MAX - @VAL_MIN - 1) * @VAL_ALEATORIO + @VAL_MIN), 0)
    RETURN @ALEATORIO
END;

SELECT dbo.NumeroAleatorio(1, 10);


