SELECT SUM(QUANTIDADE * [PREÇO]) AS TOTAL_VENDIDO
FROM dbo.[ITENS NOTAS FISCAIS]
WHERE NUMERO = 100;

CREATE FUNCTION FaturamentoNota(@NUMERO AS INT)
RETURNS FLOAT
AS 
BEGIN
    DECLARE @FATURAMENTO FLOAT

    SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO])
    FROM dbo.[ITENS NOTAS FISCAIS]
    WHERE NUMERO = @NUMERO
    RETURN @FATURAMENTO
END; 


SELECT NUMERO, dbo.FaturamentoNota(NUMERO) AS Faturamento FROM [NOTAS FISCAIS]