-- Exercício: 

-- Inclua todos os clientes na tabela CLIENTES baseados nos registros da tabela TABELA DE CLIENTES, da base SUCOS_FRUTAS.

-- Dica: cuidado com os nomes dos campos e lembre-se que já incluímos 3 clientes na nossa tabela, pelo exercício anterior.

SELECT * FROM TB_CLIENTES;

SELECT * FROM SUCOS_FRUTAS.dbo.TABELA_DE_CLIENTES;

SELECT 
    CPF,
    NOME,
    ENDERECO_1 AS ENDERECO,
    BAIRRO,
    CIDADE,
    ESTADO,
    CEP,
    DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
    IDADE,
    GENERO,
    LIMITE_DE_CREDITO AS LIMITE_CREDITO,
    VOLUME_DE_COMPRA AS VOLUME_COMPRA,
    PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.dbo.TABELA_DE_CLIENTES;

INSERT INTO TB_CLIENTES
SELECT 
    CPF,
    NOME,
    ENDERECO_1 AS ENDERECO,
    BAIRRO,
    CIDADE,
    ESTADO,
    CEP,
    DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
    IDADE,
    GENERO,
    LIMITE_DE_CREDITO AS LIMITE_CREDITO,
    VOLUME_DE_COMPRA AS VOLUME_COMPRA,
    PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.dbo.TABELA_DE_CLIENTES
WHERE CPF NOT IN ('19290992743', '2600586709');

SELECT * FROM TB_CLIENTES;