CREATE TABLE TB_PADRAO (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR(20) NULL, 
    ENDERECO VARCHAR(20) NULL, 
    CIDADE VARCHAR(20) DEFAULT 'Não informado', 
    DATA_CRIACAO DATE DEFAULT GETDATE()
);

INSERT INTO TB_PADRAO 
    (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO) 
VALUES
    ('CLIENTE X', 'RUA PROJETADA A', 'SÃO PAULO', '2018-04-30');

SELECT * FROM TB_PADRAO;

INSERT INTO TB_PADRAO 
    (DESCRITOR) 
VALUES
    ('CLIENTE Y');

SELECT * FROM TB_PADRAO;

INSERT INTO TB_PADRAO 
    (DESCRITOR) 
VALUES
    ('CLIENTE H');

SELECT * FROM TB_PADRAO;

CREATE TABLE TB_PADRAO_2 (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR(20) NULL DEFAULT 'Não informado', 
    ENDERECO VARCHAR(20) NULL DEFAULT 'Não informado', 
    CIDADE VARCHAR(20) DEFAULT 'Não informado', 
    DATA_CRIACAO DATE DEFAULT GETDATE()
);

INSERT INTO TB_PADRAO_2
    (DESCRITOR)
VALUES 
    ('CLIENTE Z');

SELECT * FROM TB_PADRAO_2;