CREATE TABLE TAB_IDENTITY (
    ID INT IDENTITY(1,1) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE X');

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE Y');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE Z');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE W');

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE A');

DELETE FROM TAB_IDENTITY WHERE ID = 1;

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE B');

DELETE FROM TAB_IDENTITY WHERE ID = 6;

INSERT INTO TAB_IDENTITY (DESCRITOR) 
VALUES ('CLIENTE C');

CREATE TABLE TAB_IDENTITY2 (
    ID INT IDENTITY(100,5) NOT NULL, 
    DESCRITOR VARCHAR (20) NULL
);

INSERT INTO TAB_IDENTITY2 (DESCRITOR) 
VALUES ('CLIENTE Y');

INSERT INTO TAB_IDENTITY2 (DESCRITOR) 
VALUES ('CLIENTE Z');