CREATE TABLE TB_FATURAMENTO
(
    DATA_VENDA DATE NULL,
    TOTAL_VENDA FLOAT
);

SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TB_VENDAS TV 
INNER JOIN TB_ITENS_VENDAS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

INSERT INTO TB_VENDAS 
VALUES (
    '0100', '2018-05-15', 1471156710, 235, 0.18
);

INSERT INTO TB_ITENS_VENDAS 
VALUES (
    '0100', '1000889', 100, 10
);

INSERT INTO TB_VENDAS 
VALUES (
    '0101', '2018-05-15', '1471156710', '235', 0.18
);

INSERT INTO TB_ITENS_VENDAS 
VALUES (
    '0101', '1000889', 100, 10
);

INSERT INTO TB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TB_VENDAS TV 
INNER JOIN TB_ITENS_VENDAS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;

INSERT INTO TB_VENDAS 
VALUES (
    '0102', '2018-05-15', '1471156710', '235', 0.18
);

INSERT INTO TB_ITENS_VENDAS 
VALUES (
    '0102', '1000889', 100, 10
);

INSERT INTO TB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TB_VENDAS TV 
INNER JOIN TB_ITENS_VENDAS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;


DELETE FROM TB_FATURAMENTO;

INSERT INTO TB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TB_VENDAS TV 
INNER JOIN TB_ITENS_VENDAS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;


SELECT * FROM TB_FATURAMENTO;

INSERT INTO TB_VENDAS 
VALUES (
    '0103', '2018-05-15', '1471156710', '235', 0.18
);

INSERT INTO TB_ITENS_VENDAS 
VALUES (
    '0103', '1000889', 100, 10
);

DELETE FROM TB_FATURAMENTO;

INSERT INTO TB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TB_VENDAS TV 
INNER JOIN TB_ITENS_VENDAS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;


SELECT * FROM TB_FATURAMENTO;

INSERT INTO TB_VENDAS 
VALUES (
    '0104', '2018-05-16', '1471156710', '235', 0.18
);

INSERT INTO TB_ITENS_VENDAS 
VALUES (
    '0104', '1000889', 100, 10
);

DELETE FROM TB_FATURAMENTO;

INSERT INTO TB_FATURAMENTO 
SELECT 
    TV.DATA_VENDA, 
    SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA 
FROM TB_VENDAS TV 
INNER JOIN TB_ITENS_VENDAS TIV 
ON TV.NUMERO = TIV.NUMERO 
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;