-- ================================================================
-- Curso 3 | Aula 05 | Atividade 05 | Preparando base para criar TRIGGER de faturamento
-- Objetivo: mostrar o processo repetitivo de recalcular TB_FATURAMENTO e
-- motivar a automatizacao com uma trigger (a ser criada depois).
-- ================================================================

-- Passo 1: criar tabela de resumo de faturamento (data x total)
CREATE TABLE TB_FATURAMENTO (
    DATA_VENDA DATE NULL,
    TOTAL_VENDA FLOAT
);

-- Passo 2: consulta base que agrega vendas e itens manualmente
SELECT
    TV.DATA_VENDA,
    SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TB_VENDAS AS TV
INNER JOIN TB_ITENS_VENDAS AS TIV
    ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

-- Passo 3: insercoes de vendas/itens simulando novos eventos
INSERT INTO TB_VENDAS VALUES ('0100', '2018-05-15', 1471156710, 235, 0.18);
INSERT INTO TB_ITENS_VENDAS VALUES ('0100', '1000889', 100, 10);
INSERT INTO TB_VENDAS VALUES ('0101', '2018-05-15', 1471156710, 235, 0.18);
INSERT INTO TB_ITENS_VENDAS VALUES ('0101', '1000889', 100, 10);

-- Passo 4: processo manual de recarga do faturamento (antes de ter trigger)
INSERT INTO TB_FATURAMENTO
SELECT
    TV.DATA_VENDA,
    SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TB_VENDAS AS TV
INNER JOIN TB_ITENS_VENDAS AS TIV
    ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO; -- valida primeira carga

-- Passo 5: inserir mais vendas e repetir a recarga (enfatiza repeticao)
INSERT INTO TB_VENDAS VALUES ('0102', '2018-05-15', 1471156710, 235, 0.18);
INSERT INTO TB_ITENS_VENDAS VALUES ('0102', '1000889', 100, 10);

INSERT INTO TB_FATURAMENTO
SELECT
    TV.DATA_VENDA,
    SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TB_VENDAS AS TV
INNER JOIN TB_ITENS_VENDAS AS TIV
    ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;

-- Passo 6: limpar e recalcular, simulando trabalho manual recorrente
DELETE FROM TB_FATURAMENTO;
INSERT INTO TB_FATURAMENTO
SELECT
    TV.DATA_VENDA,
    SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TB_VENDAS AS TV
INNER JOIN TB_ITENS_VENDAS AS TIV
    ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;

INSERT INTO TB_VENDAS VALUES ('0103', '2018-05-15', 1471156710, 235, 0.18);
INSERT INTO TB_ITENS_VENDAS VALUES ('0103', '1000889', 100, 10);

DELETE FROM TB_FATURAMENTO;
INSERT INTO TB_FATURAMENTO
SELECT
    TV.DATA_VENDA,
    SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TB_VENDAS AS TV
INNER JOIN TB_ITENS_VENDAS AS TIV
    ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;

-- Passo 7: repetir com nova data para reforcar a necessidade da trigger
INSERT INTO TB_VENDAS VALUES ('0104', '2018-05-16', 1471156710, 235, 0.18);
INSERT INTO TB_ITENS_VENDAS VALUES ('0104', '1000889', 100, 10);

DELETE FROM TB_FATURAMENTO;
INSERT INTO TB_FATURAMENTO
SELECT
    TV.DATA_VENDA,
    SUM(TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TB_VENDAS AS TV
INNER JOIN TB_ITENS_VENDAS AS TIV
    ON TV.NUMERO = TIV.NUMERO
GROUP BY TV.DATA_VENDA;

SELECT * FROM TB_FATURAMENTO;
