SELECT * FROM TB_PRODUTOS;

-- CODIGO PRODUTO A SOFRER ALTERAÇÃO DE TEXTO: 1040107

UPDATE TB_PRODUTOS SET PRECO_LISTA = 5 WHERE CODIGO = '1040107';

SELECT * FROM TB_PRODUTOS WHERE CODIGO = '1040107';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Manga';

UPDATE TB_PRODUTOS SET PRECO_LISTA = PRECO_LISTA * 1.10 WHERE SABOR = 'Manga';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Manga';

SELECT DESCRITOR FROM TB_PRODUTOS WHERE TAMANHO = '350 ml';

SELECT DESCRITOR, REPLACE(DESCRITOR, '350 ml', '550 ml') FROM TB_PRODUTOS WHERE TAMANHO = '350 ml';

UPDATE TB_PRODUTOS SET DESCRITOR = REPLACE(DESCRITOR, '350 ml', '550 ml'), TAMANHO = '550 ml' WHERE TAMANHO = '350 ml';

SELECT DESCRITOR, TAMANHO, EMBALAGEM FROM TB_PRODUTOS WHERE TAMANHO = '550 ml';

