USE [VENDAS_SUCOS]
GO

/****** Object:  Table [dbo].[TB_PRODUTOS]    Script Date: 08/10/2025 22:12:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_PRODUTOS_2](
	[CODIGO] [varchar](10) NOT NULL,
	[DESCRITOR] [varchar](100) NULL,
	[SABOR] [varchar](50) NULL,
	[TAMANHO] [varchar](50) NULL,
	[EMBALAGEM] [varchar](50) NULL,
	[PRECO_LISTA] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO TB_PRODUTOS_2 SELECT * FROM TB_PRODUTOS;

DELETE FROM TB_PRODUTOS_2;

SELECT * FROM TB_PRODUTOS_2;

DROP TABLE TB_PRODUTOS_2;