
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

SELECT
    CODIGO_DO_PRODUTO AS CODIGO,
    NOME_DO_PRODUTO AS DESCRICAO,
    SABOR,
    TAMANHO,
    EMBALAGEM,
    PRECO_DE_LISTA AS PRECO
FROM
    TABELA_DE_PRODUTOS;

SELECT
    CODIGO_DO_PRODUTO AS CODIGO,
    NOME_DO_PRODUTO AS DESCRITOR,
    SABOR,
    TAMANHO,
    EMBALAGEM,
    PRECO_DE_LISTA AS PRECO_LISTA
FROM
    SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

INSERT INTO TB_PRODUTOS 
SELECT
    CODIGO_DO_PRODUTO AS CODIGO,
    NOME_DO_PRODUTO AS DESCRITOR,
    SABOR,
    TAMANHO,
    EMBALAGEM,
    PRECO_DE_LISTA AS PRECO_LISTA
FROM
    SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;

SELECT * FROM TB_PRODUTOS;

SELECT
    CODIGO_DO_PRODUTO AS CODIGO,
    NOME_DO_PRODUTO AS DESCRITOR,
    SABOR,
    TAMANHO,
    EMBALAGEM,
    PRECO_DE_LISTA AS PRECO_LISTA
FROM
    SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS;


INSERT INTO TB_PRODUTOS 
SELECT
    CODIGO_DO_PRODUTO AS CODIGO,
    NOME_DO_PRODUTO AS DESCRITOR,
    SABOR,
    TAMANHO,
    EMBALAGEM,
    PRECO_DE_LISTA AS PRECO_LISTA
FROM
    SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO <> '1040107';

SELECT * FROM TB_PRODUTOS;