UPDATE SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS
SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;

SELECT
    A.DESCRITOR        AS PRODUTO_TB_INTERNO,
    A.PRECO_LISTA      AS PRECO_TB_INTERNO,
    B.NOME_DO_PRODUTO  AS PRODUTO_TB_EXTERNO,
    B.PRECO_DE_LISTA   AS PRECO_TB_EXTERNO
FROM TB_PRODUTOS AS A
INNER JOIN SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS AS B
    ON A.CODIGO = B.CODIGO_DO_PRODUTO;

-- Estrutura de alteração utilizando UPDATE.
UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA 
FROM PRODUTOS A 
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B 
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

-- Estrutura utilizando MERGE com UPDATE.
MERGE INTO TB_PRODUTOS A
USING SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;

SELECT
    A.DESCRITOR        AS PRODUTO_TB_INTERNO,
    A.PRECO_LISTA      AS PRECO_TB_INTERNO,
    B.NOME_DO_PRODUTO  AS PRODUTO_TB_EXTERNO,
    B.PRECO_DE_LISTA   AS PRECO_TB_EXTERNO
FROM TB_PRODUTOS AS A
INNER JOIN SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS AS B
    ON A.CODIGO = B.CODIGO_DO_PRODUTO;