SELECT * FROM TB_PRODUTOS ORDER BY CODIGO;

SELECT * FROM SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS 
ORDER BY CODIGO_DO_PRODUTO;

UPDATE SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS SET 
PRECO_DE_LISTA = PRECO_DE_LISTA * 1.20;

SELECT 
    A.DESCRITOR AS PRODUTO_TB_INTERNO,
    A.PRECO_LISTA AS PRECO_TB_INTERNO,
    B.NOME_DO_PRODUTO AS PRODUTO_TB_EXTERNO,
    B.PRECO_DE_LISTA AS PRECO_TB_EXTERNO
FROM TB_PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

UPDATE A SET A.PRECO_LISTA = B.PRECO_DE_LISTA
FROM TB_PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO;

SELECT 
    A.DESCRITOR AS PRODUTO_TB_INTERNO,
    A.PRECO_LISTA AS PRECO_TB_INTERNO,
    B.NOME_DO_PRODUTO AS PRODUTO_TB_EXTERNO,
    B.PRECO_DE_LISTA AS PRECO_TB_EXTERNO
FROM TB_PRODUTOS A
INNER JOIN SUCOS_FRUTAS.DBO.TABELA_DE_PRODUTOS B
ON A.CODIGO = B.CODIGO_DO_PRODUTO;